[workspace]
members = ["crates/flux_ecs", "crates/flux_memory/macros", "crates/flux_memory", "src/main", "crates/flux_renderer"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.94"
log = "0.4.14"
syn = "2.0.90"
quote = "1.0.37"
proc-macro2 = "1.0.92"
