[workspace]
members = [
    "crates/flux_ecs",
    "crates/flux_ecs/macros",
    "crates/flux_memory",
    "crates/flux_memory/flux_memory_macros",
    "crates/flux_renderer",
    "crates/flux_renderer/abstractions",
    "crates/flux_renderer/macros",
    "crates/flux_renderer/vulkan",
    "src/main",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.104"
log = "0.4.34"
syn = "3.0.4"
quote = "1.0.47"
proc-macro2 = "1.0.107"
criterion = "0.8.2"
proptest = "1.11.0"
trybuild = "1.0"

[workspace.lints.clippy]
mod_module_files = "deny"
