[workspace]
members = [ "crates/engine-ecs","crates/engine-macros", "crates/engine-memory"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.94"
thiserror = "2.0.7"
log = "0.4.14"
syn = "2.0.90"
quote = "1.0.37"
proc-macro2 = "1.0.92"
