[package]
name = "flux_renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
flux_renderer_abstractions = { version = "0.1.0", path = "abstractions" }
flux_renderer_macros = { version = "0.1.0", path = "macros" }
flux_renderer_vulkan = { version = "0.1.0", path = "vulkan" }

[lints]
workspace = true
